daysUntilStale: 21
daysUntilClose: 7
exemptLabels:
  - prospect
  - foundational
  - wanted
  - bug
staleLabel: stale
markComment: >
  There has been no activity on this issue for 3 weeks. It will be
  automatically closed in 1 week.

  If the issue is still relevant, please briefly explain (or remove the label).
  Feel free to reopen at any time.
closeComment: false
