name: Makefile

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get install dos2unix -y
          sudo apt-get install make -y
          sudo apt-get install coreutils -y
          sudo apt-get install default-jre -y
          sudo apt-get install default-jdk -y

      - name: Linux
        run: |
          sudo dos2unix makefile
          sudo chmod +x makefile

      - name: make
        run: |
          make

      - name: Short test
        run: |
          java -jar JavaCrypt.jar 
          java -jar JavaCrypt.jar -genkeys

      - name: Clean Up
        run: |
          rm -rf *.key
          git clean -fX
